version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - redis
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
    command: yarn start

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    command: yarn start
